name: RVNKToolKit 
version: 1.0-SNAPSHOT
author: wizard
main: org.fourz.rvnktools.RVNKTools
description: RVNK Admin Toolkit
api-version: 1.21

commands:
  ping:
    description: Shows your current ping.
    usage: /ping
  tps:
    description: Shows the server's current TPS.
    usage: /tps
  events:
    description: Provides information about scheduled events.
    usage: /events
  discord:
    description: Provides information about the server's discord.
    usage: /discord
  broadcast:
    description: Broadcasts a message to all players
    usage: /broadcast <message>
    permissions: 
      - rvnktools.command.broadcast    
  cyclegamemode:
    description: Cycle through gamemodes.
    usage: /cyclegamemode
    permissions: 
      - rvnktools.command.cyclegamemode
    alias: gmc
  cycletrainmode:
    description: Cycle through instruction sets.
    alias: railroad
    usage: /railroad
    permissions: 
      - rvnktools.command.cycletrainmode    
  countdown:  
    description: Countdown for restarting the server.
    usage: /countdown 
    permissions: 
      - rvnktools.command.countdown    

permissions:
  rvnktools.command.broadcast:
    description: Allows the player to use the broadcast command
    default: op
  rvnktools.welcome:
    description: Allows the player to get welcome messages
    default: true
  rvnktools.welcome.newplayer:
    description: Allows the player to get welcome messages
    default: true
  rvnktools.command.cyclegamemode:
    description: Allows the player to use the gmc command
    default: false
  rvnktools.command.cycletrainmode:
    description: Allows the player to use cycle railroad modes
    default: false        
        
